# build file for example01.cpp

import os

# Config
target_name = "procon_check"
src = "example01.cpp"

env = Environment(ENV=os.environ.copy())
env.ParseConfig("pkg-config sdl3 --libs-only-L --libs-only-l --cflags")
env.Append(CCFLAGS=["-std=c++2c"])

## proconlib
proconlib = {}
proconlib["include_path"] = [".."]
env.Append(CPPPATH=proconlib["include_path"])

# Executable
program = env.Program(
    target=target_name,
    source=src,
)

# Default Build Target
Default(program)
